In [1]:
import torch
import numpy as np

In [2]:
# Random seed to make results deterministic and reproducible
torch.manual_seed(0)

In [3]:
torch.cuda.device_count()

1

In [13]:
# declare dimension
input_size = 4
hidden_size = 2       #for output_size
#sequence_length = 5  #hello 를 학습시키기 위함 (하지만, Pytorch는 이 값을 자동으로 파악함!)
#batch_size = 3       #hello, eoll, lleel

In [14]:
# singleton example
# shape : (1, 1, 4)
# input_data_np = np.array([[[1, 0, 0, 0]]])

# sequential example
# shape : (3, 5, 4)
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]
input_data_np = np.array([[h, e, l, l, o], 
                          [e, o, l, l, l], 
                          [l, l, e, e, l]], 
                         dtype=np.float32)

In [15]:
# transform as torch tensor
input_data = torch.Tensor(input_data_np)

In [16]:
print(input_data, input_data.shape)

tensor([[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]],

        [[0., 1., 0., 0.],
         [0., 0., 0., 1.],
         [0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 0., 1., 0.]],

        [[0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 1., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]]]) torch.Size([3, 5, 4])


In [17]:
# declare RNN
rnn = torch.nn.RNN(input_size, hidden_size)

In [18]:
# check output
outputs, _status = rnn(input_data)
print(outputs)
print(outputs.size())

tensor([[[-0.4147,  0.5972],
         [-0.2881,  0.7695],
         [-0.8337,  0.2788],
         [-0.8337,  0.2788],
         [-0.7734,  0.7448]],

        [[-0.2018,  0.3469],
         [-0.7344,  0.2653],
         [-0.7948, -0.4056],
         [-0.7948, -0.4056],
         [-0.7842, -0.6027]],

        [[-0.8182, -0.0702],
         [-0.7993, -0.3433],
         [-0.2320,  0.6506],
         [-0.2320,  0.6506],
         [-0.8197,  0.1777]]], grad_fn=<StackBackward>)
torch.Size([3, 5, 2])


In [19]:
_status

tensor([[[-0.8182, -0.0702],
         [-0.7993, -0.3433],
         [-0.2320,  0.6506],
         [-0.2320,  0.6506],
         [-0.8197,  0.1777]]], grad_fn=<StackBackward>)