In [7]:
import torch
import torch.optim as optim
import numpy as np

In [8]:
# Random seed to make results deterministic and reproducible
torch.manual_seed(0)

In [9]:
sample = " if you want you"

In [10]:
# make dictionary
char_set = list(set(sample))
char_dic = {c: i for i, c in enumerate(char_set)}
print(type(char_set), char_set)
print(type(char_dic), char_dic)

<class 'list'> ['f', ' ', 'a', 'n', 'y', 'w', 'i', 't', 'o', 'u']
<class 'dict'> {'f': 0, ' ': 1, 'a': 2, 'n': 3, 'y': 4, 'w': 5, 'i': 6, 't': 7, 'o': 8, 'u': 9}


In [13]:
# hyper parameters
dic_size = len(char_dic)
hidden_size = len(char_dic)
learning_rate = 0.1
print(dic_size, hidden_size)

10 10


In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# data setting
sample_idx = [char_dic[c] for c in sample]
x_data = [sample_idx[:-1]]
x_one_hot = [np.eye(dic_size)[x] for x in x_data]
y_data = [sample_idx[1:]]

In [16]:
# transform as torch tensor variable
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

In [18]:
print(dic_size, hidden_size)

10 10


In [19]:
# declare RNN
rnn = torch.nn.RNN(dic_size, hidden_size, batch_first=True)

In [20]:
# loss & optimizer setting
criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(rnn.parameters(), learning_rate)

In [21]:
# start training
for i in range(50):
    optimizer.zero_grad()
    outputs, _status = rnn(X)
    loss = criterion(outputs.view(-1, dic_size), Y.view(-1))
    loss.backward()
    optimizer.step()

    result = outputs.data.numpy().argmax(axis=2)
    result_str = ''.join([char_set[c] for c in np.squeeze(result)])
    print(i, "loss: ", loss.item(), "prediction: ", result, "true Y: ", y_data, "prediction str: ", result_str)

0 loss:  2.2659921646118164 prediction:  [[2 2 2 2 2 9 9 2 9 4 4 3 4 2 4]] true Y:  [[6, 0, 1, 4, 8, 9, 1, 5, 2, 3, 7, 1, 4, 8, 9]] prediction str:  aaaaauuauyynyay
1 loss:  2.0488271713256836 prediction:  [[1 8 1 9 9 9 9 9 9 9 9 9 9 9 9]] true Y:  [[6, 0, 1, 4, 8, 9, 1, 5, 2, 3, 7, 1, 4, 8, 9]] prediction str:   o uuuuuuuuuuuu
2 loss:  1.7770426273345947 prediction:  [[1 8 1 4 8 9 1 5 4 4 8 1 4 8 9]] true Y:  [[6, 0, 1, 4, 8, 9, 1, 5, 2, 3, 7, 1, 4, 8, 9]] prediction str:   o you wyyo you
3 loss:  1.5952869653701782 prediction:  [[1 8 1 4 8 9 1 5 4 3 8 5 4 8 9]] true Y:  [[6, 0, 1, 4, 8, 9, 1, 5, 2, 3, 7, 1, 4, 8, 9]] prediction str:   o you wynowyou
4 loss:  1.4471251964569092 prediction:  [[1 0 1 4 8 9 1 5 4 3 8 5 4 8 9]] true Y:  [[6, 0, 1, 4, 8, 9, 1, 5, 2, 3, 7, 1, 4, 8, 9]] prediction str:   f you wynowyou
5 loss:  1.34563410282135 prediction:  [[1 0 1 4 8 9 1 1 4 3 7 1 4 8 9]] true Y:  [[6, 0, 1, 4, 8, 9, 1, 5, 2, 3, 7, 1, 4, 8, 9]] prediction str:   f you  ynt you
6 loss:  1.2

In [22]:
result

array([[6, 0, 1, 4, 8, 9, 1, 5, 2, 3, 7, 1, 4, 8, 9]])

In [23]:
np.squeeze(result)

array([6, 0, 1, 4, 8, 9, 1, 5, 2, 3, 7, 1, 4, 8, 9])